### ISSUE TITLE
Unavailable by ICMP ping

### ISSUE THREAD

**Issue by kkruzich** [jack-valko/Zabbix-Meraki-Discovery#13]
Following the instructions in the README file I've checked the prereqs, installed the necessary templates and tested an smpwalk from the ipaddr where zabbix is running. Yet I get these persistent 'late for check-in' and 'Unavailable by ICMP ping' messages as shown in this screenshot. Can you please tell me where to begin troubleshooting. 

![meraki_zabbix](https://user-images.githubusercontent.com/8335253/144090914-3a3396c4-bfa3-4a58-a10d-9109aaa00cfc.jpg)

**Comment by kkruzich** [comment]
I also found these ip addresses are local to the LAN at the other location. I'm unsure how these addresses were collected or if I should change them. 

![meraki_zabbix2](https://user-images.githubusercontent.com/8335253/144098962-283f6db2-457e-4100-b411-b2fffecfa2d4.jpg)

**Comment by kkruzich** [comment]
And this is the snmp configuration on the Meraki Dashboard. I am able to run the command as shown. 

![meraki_snmp](https://user-images.githubusercontent.com/8335253/144100509-f941693e-b2fd-4a85-8dba-a72ce1d4c4cb.jpg)

There are numerous warnings/errors (?) but it does seem to collect some data. 

The attached file is a mix of output, not contiguous.

[snmpwalk.txt](https://github.com/jack-valko/Zabbix-Meraki-Discovery/files/7627727/snmpwalk.txt)

**Comment by jack-valko** [comment]
Hi Kevin and thanks for reporting this issue.  There are a few things to check.

1. SNMP Settings.  The screen shot you pasted in of your SNMP setting is not what the Meraki template uses for SNMP polling.  Instead, it uses the Reporting configuration located just below this in the Meraki Dashboard UI.  You'll want to make sure this setting matches your {$SNMP_COMMUNITY} macro in Zabbix.
<img width="1126" alt="Screen Shot 2021-11-30 at 2 05 04 PM" src="https://user-images.githubusercontent.com/83570325/144135746-32f1afda-4d3a-4096-9128-22b8b5e3c4a9.png">

2. Duplicate IPs.  I noticed you are using the same IP address for multiple meraki devices (192.168.1.1).  It's perfectly okay from meraki's point of view to do this.  However, if you're going to run Zabbix to monitor your Meraki installation it needs a unique IP address for each device, otherwise it can't properly ping or poll the device.  If this is not your intent, it's possible these hosts are just misconfigured.  You should be able to correct their IP addresses from the Meraki Dashboard, delete them from Zabbix, and re-run a device discovery.

3.  Late check-in.  This warning will pop up when a meraki device hasn't checked into the cloud for a while.  It's possible these devices are switched off, or haven't been fully provisioned. 

Thank you,
Jack
