### ISSUE TITLE
MX64 issue

### ISSUE THREAD

**Issue by GC-53** [jack-valko/Zabbix-Meraki-Discovery#22]
Hi Jack,
First of all, great work! appreciate the template, and for the most part it got it working.

I have one issue however with an MX64 running the latest firmware.
From the zabbix server i can snmpwalk without issues.
I'm accessing it from the WAN side.

In zabbix the host was discovered by the template, which i fully cloned so i can modify the community string and rename it and so on. The MX64 is connected through SNMP (green), but the discovery doesn't pull in any data.

There are no errors on the discovery items at all, so i'm kind of wondering where i can look to find more info on why it isn't pulling in the interfaces.

edit: i have other MX64's that connect fine. Weird thing is that those are connecting through SNMP over their WAN ip on port 161, and the problematic MX64 has to connect over snmp.meraki.com:16100 else no go. For as far as i can see they both have the same settings configured.

Thanks!
Peter

**Comment by jack-valko** [comment]
Hey Peter,

Thanks for your report.  If I understand what's going on, you have one MX64 with the latest firmware that isn't reporting SNMP to Zabbix.  You can snmpwalk from zabbix server to the MX64 directly and get data.  You see SNMP is UP to that device, but zabbix isn't discovering items.  There should be a few items in template for the MX64 that don't require SNMP but are fetched via the web API (not snnp.meraki.com:16100), are these working?  

Can you post some screen shots of latest data on this device, and on the device configuration?  Also, are you using a zabbix proxy?  Anything relevant in zabbix_server or zabbix_proxy logs?

Jack

**Comment by GC-53** [comment]
Hi Jack,
The MX is being monitored by snmp.meraki.com:16100 because when i try to monitor it directly via the WAN ip the SNMP doesn't work. 
The template did discover the MX, and by default suggested the WAN ip as interface.
Weird thing is that the other MX's do allow monitoring via WAN ip with the exact same settings (in Meraki).
I'm puzzled why that specific MX doesn't want to work and all the others do.
Specifically because i can crawl all the OID's from the zabbix server.

The default items are actively monitored when the interface is set to snmp.meraki.com:16100
There is no proxy in place for this specific MX.
There is nothing in the zabbix server logs... i don't think i've seen anything concerning the discovery templates in the logs is that correct?

Thx 
Peter

**Comment by jack-valko** [comment]
Meraki, in their gracious wisdom, does not offer a LAN IP for an MX via the API.  The discovery operation attempts to learn the MX's LAN IP from other network devices.  If this isn't possible, it selects the WAN (or public) IP which is offered thru the API. 

If you have multiple MXs that are being monitored successfully by their WAN IP, then the issue is most likely not a firewall or broken route, or a mismatched SNMP community string.  Have you tried switching it off and back on again?  Please confirm you are not running a zabbix proxy that is set to monitor this MX.

You mentioned you could snmpwalk the device from the zabbix server that is monitoring the MX.  Can you post some output of that walk?  I would try the OID .1.3.6.1.2.1, which should give you all of the interfaces on the MX.  Also, please post a screen shot of the configure->hosts page for this device.  Thanks.
