### ISSUE TITLE
Hostname field arrives as null from API, cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by ruben-1997** [jack-valko/Zabbix-Meraki-Discovery#3]
Imported the template and haven't changed anything from the script and I applied the template throughout one of our proxies and I keep getting this error:

Cannot execute script: TypeError: cannot read property 'toLowerCase' of null
at [anon] (duktape.c:57260) internal
at [anon] (function:38) preventsyield

![image](https://user-images.githubusercontent.com/88057747/127218256-8ed74317-5434-4210-a801-4fa2586828d4.png)

Do you think you can help me?

**Comment by jack-valko** [comment]
Hello.  What name have you given to the meraki devices you expect to discover?  I can see where you might get this error if there is no device name.

**Comment by ruben-1997** [comment]
The meraki devices names are as follows:
![image](https://user-images.githubusercontent.com/88057747/127395620-e1f0a2ec-5f2a-4bc3-917c-afb59d3d2181.png)

There are more devices in our meraki instance but I'm just interested in 1 particular network that is called 'HCD-MIM' no other network in our meraki instance is of our interest.

**Comment by jack-valko** [comment]
Hello.  This issue is strange, I can't repro it.  I've updated the xml to verify the hostname it discovers from the meraki api is not null.  If it is, the device serial number is used for the hostname instead.  Since I can't repro your issue I have no idea if this will fix the problem but it should address the error message you are seeing.  Please be in touch and let me know if any new problems crop up.

**Comment by ruben-1997** [comment]
Thank you for addressing this error, It has been corrected and now I have all my devices on zabbix. Thank you for this
