### ISSUE TITLE
not able to see the packet loss trigger

### ISSUE THREAD

**Issue by naveenkesari** [jack-valko/Zabbix-Meraki-Discovery#4]
Hi,
Can we add the packet loss trigger in this template using Cisco Meraki Dashboard API v1.12.0 as below:
https://www.postman.com/meraki-api/workspace/cisco-meraki-s-public-workspace/collection/897512-42355ad3-0145-48c6-8e65-e4bb9f180939?ctx=documentation

{
 "pingId": "1",
 "url": "/devices/SERIAL/liveTools/ping/1284392014819",
 "request": {
  "serial": "Q234-ABCD-5678",
  "target": "75.75.75.75",
  "count": 2
 },
 "status": "complete",
 "results": {
  "sent": 5,
  "received": 5,
  "lossPercentage": 0,
  "latenciesInMs": {
   "minimum": 15.8,
   "mean": 15.8,
   "maximum": 15.9
  },
  "replies": [
   {
    "sequenceId": 1,
    "bytes": 84,
    "responseTimeInMs": 15.7,
    "mean": 15.8,
    "lossPercentage": 0
   },
   {
    "sequenceId": 0,
    "bytes": 84,
    "responseTimeInMs": 15.9,
    "mean": 15.9,
    "lossPercentage": 0
   }
  ]
 }
}

Thanks,
Naveen

**Comment by jack-valko** [comment]
Hi Naveen,
Thank you for your request, I'll add this to the TODO file.  One question, why is this monitor more desirable than performing ICMP checks from zabbix? 
Cheers,
Jack

**Comment by naveenkesari** [comment]
Hi Jack,

Thanks for the response however ICMP will not give you the exact packet loss event might be it will be false because source will be the Zabbix server but here via API it will check from controller to destination and which will give you the correct packet loss event.

Hope you understand.

Thanks,
Naveen

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jack-valko** [comment]
Hi Naveen,
Yes, I understand you want to measure the packet loss between the meraki device and meraki cloud.  I've added it to the TODO file, I'll try to merge this new monitor into the next release (hopefully at month end).
Cheers,
Jack

**Comment by naveenkesari** [comment]
Thanks, sounds good.

Thanks,
Naveen

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by naveenkesari** [comment]
Hi Jack,

Request you to please help on the same.

Thanks,
Naveen

**Comment by jack-valko** [comment]
Hi Naveen,

I spent some time today looking for the liveTools API call and came up blank.  If you can reference it from the [Meraki Dashboard API documentation](https://developer.cisco.com/meraki/api-v1/) I'll have another look. 

I did find an  [uplinkLossAndLatency](https://developer.cisco.com/meraki/api-v1/#!get-organization-devices-uplinks-loss-and-latency) hook that looks like this:
<pre>
$ curl -s  -L -H 'X-Cisco-Meraki-API-Key: foo' -H 'Content-Type: application/json' \ 
       -X GET 'https://api.meraki.com/api/v1/organizations/0000000/devices/uplinksLossAndLatency' 
[
    {
        "ip": "8.8.8.8",
        "networkId": "L_00000000",
        "serial": "XXXX-XXXX-XXXX",
        "timeSeries": [
            {
                "latencyMs": 36.8,
                "lossPercent": 0.0,
                "ts": "2021-09-07T18:43:31Z"
            },
            {
                "latencyMs": 38.4,
                "lossPercent": 0.0,
                "ts": "2021-09-07T18:44:30Z"
            },
            {
                "latencyMs": 40.4,
                "lossPercent": 0.0,
                "ts": "2021-09-07T18:45:30Z"
            },
            {
                "latencyMs": 91.7,
                "lossPercent": 0.0,
                "ts": "2021-09-07T18:46:30Z"
            },
            {
                "latencyMs": 48.2,
                "lossPercent": 0.0,
                "ts": "2021-09-07T18:47:31Z"
            }
        ],
        "uplink": "wan1"
    }
]
</pre>

This might give you what you want, here are a few limitations:

1. Only works if there is an MX in the organization
2. The uplink monitor may not return telemetry for the server host you want (might be stuck on 8.8.8.8)
3. Results are always in ~60 second intervals

Let me know if this is a suitable workaround for your case. 

Cheers,
Jack

**Comment by jack-valko** [comment]
Quick update on this....

I coded a script item that attempts to output this data as a 'log' datatype so that I could write triggers against it.  I think this is the best approach for this data because there are multiple values to interrogate, and the data will always arrive a few minutes late as it needs to be captured on an MX then sent to the meraki cloud before Zabbix can read it.  That process takes at least 2 minutes to complete.

After coding this it became clear that the script item output was not being parsed by Zabbix as a log.  I opened a bug on this, you can read more about it --> [https://support.zabbix.com/browse/ZBX-19925](https://support.zabbix.com/browse/ZBX-19925)

So until this gets resolved the log data option isn't possible.  I've been thinking about a different implementation, performing a discovery on each remote host and then capturing the most recent log entry as items (2 items per remote host).  This wont be great because the Zabbix timestamp will not reflect when the data was actually captured.  But it would alert you to issues on your meraki network, albeit 2 - 3 minutes late.
