### ISSUE TITLE
Is there a way to get LAN IPs for MX devices?

### ISSUE THREAD

**Issue by magicvodi** [jack-valko/Zabbix-Meraki-Discovery#5]
Hi,
my MX Devices only show up with WAN IPs in zabbix, but that doesn't work with SNMP.
Is there a way to get them with LAN IPs? Or is there an easy way to add the LAN IP manually in Zabbix?

**Comment by jack-valko** [comment]
Hi and thanks for your question.

MX appliances do not include a lanIp key/value pair in the api.  This is a decision made by Meraki.  The discovery process tries to get around this limitation and takes these steps if a device has no lanIp:

1. Check the network object to see if another device (not an MX) has reported its 'gateway', which would be a lanIp of the MX
2. If there are no other devices, default to the publicIp

The API will list a wan1 and wan2 IP for MX appliances.  Initially, I resisted using one of those IPs for the device IP because there was no lazy way to determine which one was primary, and then I'd have to track failover, etc.  I'm open to working on this logic again if this issue gets some upvotes.
